# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mahasiswa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(649, 499)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 631, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout_2.addWidget(self.pushButtonInsert)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout_2.addWidget(self.pushButtonUpdate)
        self.pushButtonDelete = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 440, 631, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout.addWidget(self.lineEditSearch)
        self.pushButtonSearch = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout.addWidget(self.pushButtonSearch)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 240, 631, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 461, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditNPM = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNPM.setObjectName("lineEditNPM")
        self.verticalLayout_2.addWidget(self.lineEditNPM)
        self.lineEditNama = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNama.setObjectName("lineEditNama")
        self.verticalLayout_2.addWidget(self.lineEditNama)
        self.lineEditKelas = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditKelas.setObjectName("lineEditKelas")
        self.verticalLayout_2.addWidget(self.lineEditKelas)
        self.lineEditJurusan = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditJurusan.setObjectName("lineEditJurusan")
        self.verticalLayout_2.addWidget(self.lineEditJurusan)
        self.lineEditTanggal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditTanggal.setObjectName("lineEditTanggal")
        self.verticalLayout_2.addWidget(self.lineEditTanggal)
        self.tableWidget.cellClicked.connect(self.getByNpm)
        self.pushButtonInsert.clicked.connect(self.insertmahasiswa)
        self.pushButtonUpdate.clicked.connect(self.updatemahasiswa)
        self.pushButtonDelete.clicked.connect(self.deletemahasiswa)
        self.pushButtonLoad.clicked.connect(self.loadmahasiswa)
        self.pushButtonSearch.clicked.connect(self.seachmahasiswa)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def getByNpm(self,row):
        try:
            npm = self.tableWidget.item(row,0)
            nama = self.tableWidget.item(row,1)
            kelas = self.tableWidget.item(row,2)
            jurusan = self.tableWidget.item(row,3)
            ttl = self.tableWidget.item(row,4)
            if npm :
                valuenpm = npm.text()
                valuenama = nama.text()
                valuekelas = kelas.text()
                valuejurusan = jurusan.text()
                valuettl = ttl.text()
                self.lineEditNPM.setText(valuenpm)
                self.lineEditNama.setText(valuenama)
                self.lineEditKelas.setText(valuekelas)
                self.lineEditJurusan.setText(valuejurusan)
                self.lineEditTanggal.setText(valuettl)
            self.label_3.setText("Data Mahasiswa Berhasil Di Pilih")
        except mc.Error as Err:
            self.label_3.setText("Data Mahasiswa Gagal Di Pilih")
        
    def insertmahasiswa(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_kampus"
            )
            cursor = mydb.cursor()
            npm = self.lineEditNPM.text()
            nama = self.lineEditNama.text()
            kelas = self.lineEditKelas.text()
            jurusan = self.lineEditJurusan.text()
            ttl = self.lineEditTanggal.text()
            
            sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tanggal_lahir) VALUES (%s,%s,%s,%s,%s)"
            val = (npm, nama, kelas, jurusan, ttl)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_3.setText("Data Mahasiswa Berhasil Disimpan")
            self.lineEditNPM.setText("")
            self.lineEditNama.setText("")
            self.lineEditKelas.setText("")
            self.lineEditJurusan.setText("")
            self.lineEditTanggal.setText("")
        except mc.Error as Err:
            self.label_3.setText("Data Mahasiswa Gagal Di Simpan")
            
    def updatemahasiswa(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_kampus"
            )
            cursor = mydb.cursor()
            npm = self.lineEditNPM.text()
            nama = self.lineEditNama.text()
            kelas = self.lineEditKelas.text()
            jurusan = self.lineEditJurusan.text()
            ttl = self.lineEditTanggal.text()
            
            sql = "UPDATE mahasiswa SET nama = (%s), kelas = (%s), jurusan = (%s), tanggal_lahir = (%s) WHERE npm = (%s)" 
            val = (nama, kelas, jurusan, ttl, npm)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_3.setText("Data Mahasiswa Berhasil Di Update")
            self.lineEditNPM.setText("")
            self.lineEditNama.setText("")
            self.lineEditKelas.setText("")
            self.lineEditJurusan.setText("")
            self.lineEditTanggal.setText("")
        except mc.Error as e:
            self.label_3.setText("Data Mahasiswa Gagal Di Update")
    
    def deletemahasiswa(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_kampus"
            )
            cursor = mydb.cursor()
            npm = self.lineEditNPM.text()
            
            sql = "DELETE FROM mahasiswa WHERE npm = %s"
            val = (npm,)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_3.setText("Data Mahasiswa Berhasil Di Hapus")
            self.lineEditNPM.setText("")
            self.lineEditNama.setText("")
            self.lineEditKelas.setText("")
            self.lineEditJurusan.setText("")
            self.lineEditTanggal.setText("")
        except mc.Error as e:
            self.label_3.setText("Data Mahasiswa Gagal Di Hapus")
    
    def loadmahasiswa(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_kampus"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.label_3.setText("Data Mahasiswa Berhasil Ditampilkan")
        except mc.Error as e:
            self.label_3.setText("Data Mahasiswa Gagal Ditampilkan")
    
    def seachmahasiswa(self):
        try:
            mydb = mc.connect(
                host = "localhost",
                user = "root",
                password = "",
                database = "db_kampus"
            )
            cursor = mydb.cursor()
            srckat = self.lineEditSearch.text()
            
            sql = "SELECT * FROM mahasiswa WHERE npm LIKE %s OR nama LIKE %s OR kelas LIKE %s OR jurusan LIKE %s OR tanggal_lahir LIKE %s ORDER BY npm ASC"
            val = (f"%{srckat}%", f"%{srckat}%", f"%{srckat}%", f"%{srckat}%", f"%{srckat}%")
            cursor.execute(sql,val)
            result = cursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.label_3.setText("Hasil Search Data Mahasiswa")
            self.lineEditSearch.setText("")
        except mc.Error as e:
            self.label_3.setText("Pencarian Gagal")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.pushButtonInsert.setText(_translate("Form", "INSERT"))
        self.pushButtonUpdate.setText(_translate("Form", "UPDATE"))
        self.pushButtonDelete.setText(_translate("Form", "DELETE"))
        self.pushButtonLoad.setText(_translate("Form", "LOAD DATA"))
        self.pushButtonSearch.setText(_translate("Form", "Searching"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tanggal Lahir"))
        self.label_2.setText(_translate("Form", "NPM"))
        self.label_5.setText(_translate("Form", "Nama"))
        self.label_4.setText(_translate("Form", "Kelas"))
        self.label_6.setText(_translate("Form", "Jurusan"))
        self.label.setText(_translate("Form", "Tanggal Lahir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
